### ISSUE TITLE
support for resolve

### ISSUE THREAD

**Issue by ShahOdin** [2m/ciris-hocon#184]
does it support resolving terms?

ie 

```
foo{
  bar = 123
}
baz{
  qux = ${foo.bar}
}
```

I got an error when i tried it but haven't tried to create a minimal example yet.

**Comment by 2m** [comment]
Good catch. `Config` instance that is passed to `hoconAt` might not have been resolved. So I added `resolve()` called to the factory method: #185

**Comment by 2m** [comment]
Released `1.0.1` with the fix.
